// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2HZSILOh0Po_Zouo-60QSWIo6fz0sVCs',
    appId: '1:953132250973:android:b7917888b7e38791601ab4',
    messagingSenderId: '953132250973',
    projectId: 'ultimate-alarm-clock-df2ad',
    storageBucket: 'ultimate-alarm-clock-df2ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaDGcB7oYDgDj3nEBZkatYDXtp3PCm838',
    appId: '1:953132250973:ios:47d0510f5e0bc4ab601ab4',
    messagingSenderId: '953132250973',
    projectId: 'ultimate-alarm-clock-df2ad',
    storageBucket: 'ultimate-alarm-clock-df2ad.appspot.com',
    androidClientId:
        '953132250973-vknv8icismgokn4nu0hu0sudh668hgi5.apps.googleusercontent.com',
    iosClientId:
        '953132250973-dse3ntm24v8klf2e36t1qbop1ul42uvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarmx',
  );
}
